smartcar/node-sdk

package.json
test/unit/index.js
test/unit/lib/auth-client.js
test/unit/lib/errors.js
test/unit/lib/util.js
test/unit/lib/vehicle.js

Moved all the existing tests to a unit test folder.

refactor(test): moved tests to a unit test folder

---

README.md
doc/readme.md
lib/auth-client.js

Commit to trigger release for https://github.com/smartcar/node-sdk/commit/f4caad30bd978386acbb7bb4a4f8607a21d474d1.
Also updated read me code snippet.
Confirm the commit message adheres to semantic release guidelines for triggering a release.

feat(mode): change development flag to testMode flag

---

README.md
doc/readme.md
lib/auth-client.js
test/end-to-end/auth-client.js
test/unit/lib/auth-client.js

@gurpreetatwal I don't know if we need to add an additional README section on compatibility? I think I might add a guide to the Doc Center instead.

Add Compatibility

---

doc/readme.md
lib/auth-client.js
package-lock.json
test/end-to-end/helpers/index.js
test/unit/index.js
test/unit/lib/auth-client.js
test/unit/lib/util.js

See https://github.com/smartcar/oem-auth/pull/401

Adds support for Connect's vehicleInfo query param

---

doc/readme.md
lib/auth-client.js
test/end-to-end/auth-client.js
test/unit/lib/auth-client.js

**NOTE:** e2e will fail as compatibility is not yet published on API.

feat: Add Compatibility of Functions

---

doc/readme.md
lib/errors.js
lib/util.js
test/end-to-end/helpers/index.js
test/unit/lib/util.js

Asana: https://app.asana.com/0/1112517589407256/1119119801535131

fix: Make authentication error great again

---

doc/readme.md
lib/errors.js
lib/util.js
test/end-to-end/helpers/index.js
test/unit/lib/errors.js
test/unit/lib/util.js

Add `code` to vehicle state errors

Feat: Vehicle state errors

---

doc/readme.md
lib/vehicle.js
test/end-to-end/vehicle.js
test/unit/lib/vehicle.js

Added vehicle has permissions to check if a vehicle contains a certain permission in prep for Connect Single Select.

feat: Vehicle has permission

---

lib/config.json
lib/util.js

Set the timeout to match Smartcar's api's max timeout: https://github.com/request/request#requestoptions-callback

fix(timeout): set explicit timeout to 300 seconds

---

doc/readme.md
lib/vehicle.js
test/end-to-end/helpers/index.js
test/end-to-end/vehicle.js
test/unit/lib/vehicle.js

https://app.asana.com/0/1135848224816825/1178967344640613

Add start and stop charge

---

lib/auth-client.js
test/end-to-end/auth-client.js
test/end-to-end/index.js
test/end-to-end/vehicle.js

Asana: https://app.asana.com/0/1200551405669439/1200639349239326/f

fix: tests for compatibility v2

---

lib/util.js

BREAKING CHANGE: dummy commit to bump major version.

BREAKING CHANGE: bumping version

---

doc/readme.md
index.js

Updates `smartcar.getCompatibility` docs with Compatibility v2 response type
Asana: https://app.asana.com/0/1122465745219696/1201987199141657/f

chore: updates docs with v2 compatibility info

---

README.md
doc/readme.md
index.js
lib/auth-client.js
lib/vehicle.js
package.json
test/end-to-end/helpers/index.js
test/unit/index.js
test/unit/lib/auth-client.js
test/unit/lib/vehicle.js

Adding support for simulated mode and compatibility feature flags
Asana: https://app.asana.com/0/1202541719267260/1202555728616887/f

feat(smartcar): added support for simulated mode and feature flags

---

.gitignore
doc/readme.md
lib/vehicle.js
package-lock.json
package.json
test/end-to-end/vehicle.js
test/unit/lib/vehicle.js

Adds two new functions to the vehicle object, `getChargeLimit` and `setChargeLimit`
Asana: https://app.asana.com/0/1204073873904879/1204302264096972/f
- Added [`sinon`](https://www.npmjs.com/package/sinon) as a dev dependency to allow for creating spys in our test.

feat(vehicle): get & set charge limit

---

doc/readme.md
index.js
lib/config.json
lib/util.js
package.json
test/end-to-end/helpers/index.js
test/end-to-end/index.js
test/end-to-end/vehicle.js
test/unit/index.js
test/unit/lib/util.js

This PR adds functions in the smartcar namespace for Vehicle Management API.
Asana: https://app.asana.com/0/1205137826392826/1205221447377578

vehicle management functions

---

doc/readme.md
lib/smartcar-service.js
lib/vehicle.js
test/end-to-end/vehicle.js

We added the security path in the map to translate it to lockStatus
Asana: https://app.asana.com/0/1205281929337658/1205139255747900/f

fix(batch): Fix the lock status method name in batching

---

doc/readme.md
lib/auth-client.js
test/unit/lib/auth-client.js

Adding the new optional `user` option for `getAuthUrl`

feat: add user option to getAuthUrl

---

doc/readme.md
lib/smartcar-error.js
test/end-to-end/util.js
test/unit/lib/vehicle.js

Asana: https://app.asana.com/0/0/1206993255628961/f

feat: add suggestedUserMessage to smartcar error

---

lib/util.js

BREAKING CHANGE: dummy commit to bump major version.

BREAKING CHANGE: bump version
